name: Dispatch Deploy

on:
  push:
    branches: [master]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger code repo build
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          repository: yujing0208/yujingblog
          event-type: content-update
