name: Trigger Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        run: |
          curl -s -X POST "https://api.github.com/repos/yujing0208/yujingblog/dispatches" \
            -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"event_type":"content-updated"}'
